/**
 * The sprig, as path data in a 0 0 192 192 viewBox.
 *
 * GENERATED by scripts/make-icons.mjs — edit the geometry there, not here,
 * or the header mark and the app icon stop being the same drawing.
 */
export const SPRIG_VIEWBOX = '0 0 192 192';
export const SPRIG_STROKE_WIDTH = 9;
export const SPRIG_STEM = 'M92,160C88,134 98,104 110,58';
export const SPRIG_LEAVES = [
  'M91.2,143.8C92.5,106.4 61.4,101.4 31.8,119.8C38.2,145.1 66.2,161.3 91.2,143.8',
  'M94.6,118.5C118.2,142.9 141,125.7 147.6,94.9C127.1,83.2 98.9,91.1 94.6,118.5',
  'M101.9,88.5C107,59.7 83.4,52.5 58.6,63.5C60.8,83.7 80.6,99.3 101.9,88.5',
  'M110,58C135.5,54.4 135.2,32.8 119.1,15C102.8,22.3 95.2,43.2 110,58',
];
