/* ============================================================
   ICONS — one hand, the same hand as the drawings.

   The glyphs live in iconPaths.ts, which is GENERATED by
   scripts/make-icons-set.mjs; the construction contract they hold to is
   stated at the top of that script.

   They replace a set ported from the vanilla app, which was competent and
   entirely generic: uniform strokes, perfect circles, mirror-symmetric
   glyphs. That set broke every rule the course tree and the app mark are
   built on, which is what made the app read as a template with good artwork
   pasted into it rather than as one object.
   ============================================================ */

import { ICON_PATHS, type IconName } from './iconPaths';

export type { IconName };

interface IconProps {
  name: IconName;
  size?: number;
  className?: string;
}

export function Icon({ name, size = 16, className }: IconProps) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      // No strokeWidth here: each mark carries its own, because an outer
      // contour is heavier than the marks inside it.
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      focusable="false"
      className={className}
      // Static, code-authored constants above — never user or course content.
      dangerouslySetInnerHTML={{ __html: ICON_PATHS[name] }}
    />
  );
}
