/**
 * Draws the app icon and writes public/icons/*.
 *
 *   node scripts/make-icons.mjs
 *
 * The mark is a sprig: one stem, four leaves, drawn the way the course tree
 * is drawn — placed curves, no primitives, no mirror symmetry, leaves filled
 * with the paper colour so they occlude the stem behind them.
 *
 * It is NOT the course tree itself. That was tried first: the generated tree
 * is several hundred leaves, and below about 64px every version of it
 * collapsed into a grey smudge. An icon has to survive at 32px in a browser
 * tab, so it gets a mark of the same hand with a tenth of the marks.
 *
 * The tile keeps its own light paper background in both themes, because a
 * home-screen or tab icon is composited by the OS and cannot follow one.
 *
 * It also writes src/lib/sprigMark.ts, so the header wordmark and the app
 * icon are the same drawing rather than two that drift apart.
 *
 * PNG rasterisation needs playwright on the path; without it the script
 * still writes the SVGs and tells you which PNGs to render by other means.
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'public', 'icons');

/** Matches --color-bg and --color-text in the light theme. */
const PAPER = '#e2e0d5';
const INK = '#1b1d1f';

const r2 = (n) => Math.round(n * 10) / 10;

/** A point on a cubic, so every leaf is anchored exactly on the stem. */
function onCurve(p, t) {
  const u = 1 - t;
  const [a, b, c, d] = [u * u * u, 3 * u * u * t, 3 * u * t * t, t * t * t];
  return [
    a * p[0][0] + b * p[1][0] + c * p[2][0] + d * p[3][0],
    a * p[0][1] + b * p[1][1] + c * p[2][1] + d * p[3][1],
  ];
}

/**
 * One leaf: two different curves either side of the midrib, so it is never
 * its own reflection. w1/w2 are the two bulges, as a fraction of length.
 */
function leaf(bx, by, deg, len, w1, w2) {
  const a = (deg * Math.PI) / 180;
  const [dx, dy] = [Math.sin(a), -Math.cos(a)];
  const [px, py] = [-dy, dx];
  const at = (t, o) => `${r2(bx + dx * len * t + px * len * o)},${r2(by + dy * len * t + py * len * o)}`;
  return (
    `M${r2(bx)},${r2(by)}` +
    `C${at(0.2, w1)} ${at(0.68, w1 * 0.8)} ${at(1, 0)}` +
    `C${at(0.76, -w2 * 0.82)} ${at(0.26, -w2)} ${r2(bx)},${r2(by)}`
  );
}

// The stem leans and thins; leaves alternate sides at uneven intervals and
// shorten towards the tip, which is what keeps it from looking stamped out.
const STEM = [[92, 160], [88, 134], [98, 104], [110, 58]];
const LEAVES = [[0.2, -68, 64], [0.48, 66, 58], [0.76, -60, 50]];
const TIP = [12, 44];
// A heavy stroke on a narrow leaf squeezes the paper interior to a sliver and
// the leaf reads as a fat comma, so the two move together.
const [W1, W2] = [0.55, 0.4];

/** The stem, then one path per leaf. */
function geometry() {
  const stem = `M${STEM[0]}C${STEM[1]} ${STEM[2]} ${STEM[3]}`.replace(/,(\d)/g, ',$1');
  const leaves = LEAVES.map(([t, deg, len]) => {
    const [x, y] = onCurve(STEM, t);
    return leaf(x, y, deg, len, W1, W2);
  });
  const [tx, ty] = onCurve(STEM, 1);
  leaves.push(leaf(tx, ty, TIP[0], TIP[1], W1, W2));
  return { stem, leaves };
}

function mark(scale = 1) {
  const { stem, leaves } = geometry();
  const parts = [`<path d="${stem}"/>`, ...leaves.map((d) => `<path d="${d}" fill="${PAPER}"/>`)];

  const g =
    `<g fill="none" stroke="${INK}" stroke-width="9" stroke-linecap="round" stroke-linejoin="round">` +
    parts.join('') +
    `</g>`;
  return scale === 1 ? g : `<g transform="translate(96 96) scale(${scale}) translate(-96 -96)">${g}</g>`;
}

/** `rx` 0 is the maskable/full-bleed tile; the OS supplies the shape. */
function tile({ rx = 40, scale = 1 } = {}) {
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192">` +
    `<rect width="192" height="192"${rx ? ` rx="${rx}"` : ''} fill="${PAPER}"/>` +
    mark(scale) +
    `</svg>`
  );
}

const ROUNDED = tile();
// Maskable art is cropped to a circle by some launchers, so the mark sits
// inside the 80% safe zone and the paper runs to the edge.
const MASKABLE = tile({ rx: 0, scale: 0.72 });

fs.mkdirSync(OUT, { recursive: true });
fs.writeFileSync(path.join(OUT, 'icon.svg'), ROUNDED + '\n');

// The same geometry, for the wordmark in the app header.
const { stem, leaves } = geometry();
fs.writeFileSync(
  path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'src', 'lib', 'sprigMark.ts'),
  `/**\n * The sprig, as path data in a 0 0 192 192 viewBox.\n *\n * GENERATED by scripts/make-icons.mjs — edit the geometry there, not here,\n * or the header mark and the app icon stop being the same drawing.\n */\nexport const SPRIG_VIEWBOX = '0 0 192 192';\nexport const SPRIG_STROKE_WIDTH = 9;\nexport const SPRIG_STEM = '${stem}';\nexport const SPRIG_LEAVES = [\n${leaves
    .map((d) => `  '${d}',`)
    .join('\n')}\n];\n`,
);

const PNGS = [
  ['icon-192.png', ROUNDED, 192],
  ['icon-512.png', ROUNDED, 512],
  ['icon-maskable-512.png', MASKABLE, 512],
  // iOS applies its own mask and ignores transparency, so this one is
  // full-bleed square rather than pre-rounded.
  ['apple-touch-icon.png', tile({ rx: 0 }), 180],
];

let chromium;
try {
  ({ chromium } = await import('playwright'));
} catch {
  console.log('icon.svg written. playwright not found — render these from it by hand:');
  for (const [name, , size] of PNGS) console.log(`  ${name} (${size}px)`);
  process.exit(0);
}

const browser = await chromium.launch();
for (const [name, svg, size] of PNGS) {
  const page = await browser.newPage({ viewport: { width: size, height: size } });
  await page.setContent(
    `<style>html,body{margin:0;padding:0}svg{width:${size}px;height:${size}px;display:block}</style>${svg}`,
  );
  await page.screenshot({ path: path.join(OUT, name), omitBackground: true });
  await page.close();
  console.log(`wrote ${name}`);
}
await browser.close();
console.log('wrote icon.svg');
